/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package travel;

import travel.persistence.FileDataStore;

public class Application {
    private final FileDataStore dataStore = new FileDataStore("data");

    public static void main(String[] args) {
        new Application().run();
    }

    private void run() {
        dataStore.loadData();
    }
}
