/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package travel;
import java.util.Scanner;

import travel.persistence.DataStore;
import travel.persistence.FileDataStore;
import travel.service.DefaultTravelService;
import travel.service.TravelService;
import travel.view.ConsoleView;

import java.util.Scanner;

public class Application{
    private final DataStore dataStore = new FileDataStore("data");
    private final TravelService travelService = new DefaultTravelService(dataStore);
    private final View consoleView = new ConsoleView(travelService);

    public static void main(String[] args) {
        new Application().run();
    }

    private void run() {
        dataStore.loadData();
        consoleView.Run();
    }
}
